### ISSUE TITLE
CKA_ALLOWED_MECHANISMS

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#182]
Look at support for CKA_ALLOWED_MECHANISMS, as the TPM can support a list of 1.

**Comment by PeterHuewe** [comment]
Can you elaborate a bit more on this? 
By this description I find it hard to implement.

**Comment by williamcroberts** [comment]
The code is using this when checking if an object supports a particular mechanism. In the future, the gen_mech's calls in the C and Python code need to be smart enough to populate this completely.

The TPM attribute handling code needs to also interrogate if this is specified in the template and adjust the scheme on the TPM public template portion. Currently, we just build keys with scheme set to TPM2_ALG_NULL so all possible mechanisms are supported.

**Comment by williamcroberts** [comment]
Currently, CKA_ALLOWED_MECHANISMS gets populated for objects based on the object supporting raw rsa (scheme is null). So we need to create keys now with CKA_ALLOWED_MECHANISMS with a length of 1 mechanism, and then tie that mechanism in by setting the scheme field when creating to that mechanism.

**Comment by tracefinder** [comment]
Hi!
I got the same problem. Keys are created with golang (mostly based on https://ericchiang.github.io/post/tpm-keys/).
For my needs I use `link` command, but get the following error
```
Stderr:
Traceback (most recent call last):
  File "/usr/bin/tpm2_ptool", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/usr/lib/python3.11/site-packages/tpm2_pkcs11/command.py", line 102, in init
    commandlet.get()[d['which']](d)
  File "/usr/lib/python3.11/site-packages/tpm2_pkcs11/commandlets_keys.py", line 699, in __call__
    objects = super(LinkCommand, self).__call__(args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tpm2_pkcs11/commandlets_keys.py", line 211, in __call__
    return NewKeyCommandBase.new_key_save(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tpm2_pkcs11/commandlets_keys.py", line 137, in new_key_save
    objects = PKCS11ObjectFactory(y, tpm2, encobjauth, initial_pubattrs, initial_privattrs,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tpm2_pkcs11/objects.py", line 405, in PKCS11ObjectFactory
    raise RuntimeError('Cannot map scheme to allowed mechanism, got: "{}"'.format(scheme))
RuntimeError: Cannot map scheme to allowed mechanism, got: "ecdsa"
```

It works okay for RSA, because in that case scheme is None. However, it is different for ECC. My current workaround is to change [this line](https://github.com/tpm2-software/tpm2-pkcs11/blob/1b3aab90ee5f7debbce82c7e229aa2950a9e8f0d/tools/tpm2_pkcs11/objects.py#L403) to `if scheme != None and scheme != 'ecdsa':`

Any thought how it can be resolved?

**Comment by williamcroberts** [comment]
> Any thoughts how it can be resolved?

Do what the comment says right above it to support non-null schemes.
```python3
    # if we need to support non-null schemes we need to map tpm2 alg to pkcs11 alg
    # and populate CKA_ALLOWED_MECHANISMS and skip calling genmechs()
````

**Comment by tracefinder** [comment]
@williamcroberts could you, please, make it more clear? I'm trying to get the idea behind working only with a null scheme.
I see that `genmechs()` just lists available TPM algorithms and adds relevant mechanisms to `CKA_ALLOWED_MECHANISMS`.
So,is the idea of the comment you quoted to do it in advance?  Or are there situations when a non-null scheme brings a completely different list of mechanisms that current `genmechs` implementations don't cover?

**Comment by williamcroberts** [comment]
> @williamcroberts could you, please, make it more clear? I'm trying to get the idea behind working only with a null scheme. I see that `genmechs()` just lists available TPM algorithms and adds relevant mechanisms to `CKA_ALLOWED_MECHANISMS`. So,is the idea of the comment you quoted to do it in advance? Or are there situations when a non-null scheme brings a completely different list of mechanisms that current `genmechs` implementations don't cover? I guess the latter is the problem. Someone needs to implement restrictions based on TPM object's attributes.

They way that it works is that the `CKA_ALLOWED_MECHANISMS` is a list of the supported schemes, so to check if a mechanism is supported is to just query it against this list. So if the object has a set scheme, ie is not the null scheme, the list of mechanisms in CKA_ALLOWED_MECHANISMS would be just that scheme.

So it's just a matter of skipping gen_mechs if scheme is set, mapping the TPM2_ALG for scheme to a `CKA_MECHANISM` and then populating the `CKA_ALLOWED_MECHANISMS` list with that one entry and letting the existing flow store it to the db.
