### ISSUE TITLE
TPM Error 0xa0008 on login/token creation

### ISSUE THREAD

**Issue by reanimus** [tpm2-software/tpm2-pkcs11#189]
I'm seeing this show up when I try to log in, as well as during certain actions with tpm2-ptool.

I have my system set up to pull the latest builds for tpm2-tss, tpm2-tools, and tpm2-pkcs11, so I'm running the latest revisions of all three.

I migrated my database earlier (from using the attrs -> privattrs/pubattrs) but once I got that done, I'm getting this when I try to log in:

```
Enter PIN for 'Fenrisulfr': 
WARNING:tcti:src/tss2-tcti/tcti-device.c:254:tcti_device_receive() Got EOF instead of response. 
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:338:Esys_RSA_Decrypt_Finish() Received a non-TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:130:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x000a0008) 
ERROR: Esys_RSA_Decrypt: 0xa0008
C_Sign failed: 5
sign_and_send_pubkey: signing failed: error in libcrypto
```

I tried creating a new token + key, adding the new pubkey to the authorized_keys, then trying that one, but it had the same result. Additionally, during the creation of the new token, I saw this:

```
animus@Fenrir ~/Development/tpm2-pkcs11/tools $ ./tpm2_ptool addtoken --pid 1 --sopin SOPIN --userpin USERPIN --label Test
auto-detecting TPM encryptdecrypt interface for wrapping key usage
Using "Software" based object authorization protections
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/animus/Development/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 28, in <module>
    main()
  File "/home/animus/Development/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 24, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/home/animus/Development/tpm2-pkcs11/tools/tpm2_pkcs11/command.py", line 62, in init
    commandlet.get()[d['which']](d)
  File "/home/animus/Development/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_token.py", line 422, in __call__
    AddTokenCommand.do_token_init(db, path, args)
  File "/home/animus/Development/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_token.py", line 319, in do_token_init
    seal=wrappingobjauth['hash'])
  File "/home/animus/Development/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 148, in create
    str(stderr))
RuntimeError: Could not execute tpm2_create: b'WARNING:tcti:src/tss2-tcti/tcti-device.c:254:tcti_device_receive() Got EOF instead of response. \nERROR:esys:src/tss2-esys/api/Esys_Create.c:416:Esys_Create_Finish() Received a non-TPM Error \nERROR:esys:src/tss2-esys/api/Esys_Create.c:156:Esys_Create() Esys Finish ErrorCode (0x000a0008) \nERROR: Esys_Create(0xA0008) - tcti:Fails to connect to next lower layer\nERROR: Unable to run tpm2_create\n'
animus@Fenrir ~/Development/tpm2-pkcs11/tools $ ./tpm2_ptool addtoken --pid 1 --sopin SOPIN --userpin USERPIN --label Test
auto-detecting TPM encryptdecrypt interface for wrapping key usage
Using "Software" based object authorization protections
Created token label: Test
```

So the first invocation fails, but the second doesn't.

**Comment by tstruk** [comment]
What kernel version is it on? It might be related to this bug:
https://marc.info/?l=linux-integrity&m=155216873820715&w=2

**Comment by reanimus** [comment]
Linux Fenrir 5.0.5-gentoo #2 SMP Sun Mar 31 14:55:43 PDT 2019 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux

Good catch!

**Comment by tstruk** [comment]
It is fixed upstream with this commit: https://git.kernel.org/pub/scm/linux/kernel/git/jmorris/linux-security.git/commit/?h=next-tpm&id=7bde1fe0abbe202dc1f484fe7ef110f6ed3b1351

**Comment by reanimus** [comment]
I'll add that patch to my local kernel builds till it lands in the main kernel release. Thanks!

**Comment by reanimus** [comment]
Just rebooted with the kernel patch applied and the error is gone, so I'm closing this out.
