### ISSUE TITLE
tpm2_ptool : could not convert port to a 16 unsigned number

### ISSUE THREAD

**Issue by r4yv3n** [tpm2-software/tpm2-pkcs11#268]
Just looking at tpm2 for the first time.Still a bit confused how all the tpm-tools fit together. Here I'm just focused on getting to the point of using pkcs11-tools and other pkcs11 enabled tools. In trying to follow the instructions for initializing "tpm2_ptool.py init --pobj-pin=mypobjpin --path=~/tmp".  I run into the issue shown at the bottom. At first glance it looks like the command option might be wrong or I have something configured wrong. 

Ubuntu 18.04 

apt packages install
-tpm2-pk11     
-tpm2-tools                                                                                  
-tss2

compiled and installed
-tpm2-abrmd
  tss      27706   00:00:00 /usr/local/sbin/tpm2-abrmd
-tpm2-pkcs11
   /usr/lib/x86_64-linux-gnu/pkcs11/libtpm2_pkcs11.so

TPM2TOOLS_TCTI_NAME=device
TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0

tools that return good information
-tpm2_listpcrs 
      Bank/Algorithm: TPM_ALG_SHA1(0x0004)
      Bank/Algorithm: TPM_ALG_SHA256(0x000b)

-tpm2_nvlist 
  0. NV Index: 0x1800001
  1. NV Index: 0x1800003
  2. NV Index: 0x1800004
  3. NV Index: 0x1c00002
  4. NV Index: 0x1c0000a

tpm2_getrandom -o random.out 20
hexdump -C random.out 
00000000  6c 43 f2 43 f0 6b 97 fa  7a 0a c1 6e 7f 30 90 2c  |lC.C.k..z..n.0.,|
00000010  9b f8 66 ac 

tpm2_listpersistent  0 persistent objects defined.

tpm2-pkcs11/tools/tpm2.py
    def createprimary(self, ownerauth, objauth):
        ctx = os.path.join(self._tmp, "context.out")
        cmd = [
            'tpm2_createprimary', **'-p',** 'hex:%s' % objauth.decode(), '-o', ctx,
            '-g', 'sha256', '-G', 'rsa'
        ]

       **-p, --socket-port
              Specify the port number used by the socket TCTI. The default is 2321.**

**************** Error running tpm2_ptool.py ***********************

ctx = /tmp/tmphpH8lS/context.out
cmd = ['tpm2_createprimary', '-p', u'hex:00834148fb6361d0e3c952d18371fb7748ad1a0a6c837ce28a28bac25dc7bc89', '-o', '/tmp/tmphpH8lS/context.out', '-g', 'sha256', '-G', 'rsa']

Traceback (most recent call last):
  File "/root/Source/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 95, in __call__
    ctx = tpm2.createprimary(ownerauth, pobjauth)
  File "/root/Source/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2.py", line 33, in createprimary
    stderr)
RuntimeError: Could not execute tpm2_createprimary: ERROR: Could not convert port to a 16 bit unsigned number, got: hex:00834148fb6361d0e3c952d18371fb7748ad1a0a6c837ce28a28bac25dc7bc89
free(): invalid pointer

Could not execute tpm2_createprimary: ERROR: Could not convert port to a 16 bit unsigned number, got: hex:00834148fb6361d0e3c952d18371fb7748ad1a0a6c837ce28a28bac25dc7bc89
free(): invalid pointer

**Comment by r4yv3n** [comment]
PASS: test/integration/auth-session-max.int
PASS: test/integration/auth-session-start-flush.int
PASS: test/integration/auth-session-start-save.int
PASS: test/integration/auth-session-start-save-load.int
PASS: test/integration/max-transient-upperbound.int
PASS: test/integration/get-capability-handles-transient.int
PASS: test/integration/manage-transient-keys.int
PASS: test/integration/session-gap.int
PASS: test/integration/session-load-from-closed-connection.int
PASS: test/integration/session-load-from-closed-connections-lru.int
PASS: test/integration/session-load-from-open-connection.int
XFAIL: test/integration/start-auth-session.int
PASS: test/integration/tcti-cancel.int
PASS: test/integration/tcti-connections-max.int
PASS: test/integration/tcti-double-finalize.int
PASS: test/integration/tcti-set-locality.int
PASS: test/integration/hash-sequence.int
PASS: test/integration/not-enough-handles-for-command.int
PASS: test/integration/password-authorization.int
PASS: test/integration/tpm2-command-flush-no-handle.int
PASS: test/integration/util-buf-max-upper-bound.int
PASS: test/access-broker_unit
PASS: test/command-attrs_unit
PASS: test/connection_unit
PASS: test/connection-manager_unit
PASS: test/logging_unit
PASS: test/message-queue_unit
PASS: test/resource-manager_unit
PASS: test/response-sink_unit
PASS: test/command-source_unit
PASS: test/handle-map-entry_unit
PASS: test/handle-map_unit
PASS: test/ipc-frontend_unit
PASS: test/ipc-frontend-dbus_unit
PASS: test/random_unit
PASS: test/session-entry_unit
PASS: test/session-list_unit
PASS: test/tabrmd-init_unit
PASS: test/tabrmd-options_unit
PASS: test/test-skeleton_unit
PASS: test/tcti_unit
PASS: test/tcti-factory_unit
PASS: test/tcti-util_unit
PASS: test/thread_unit
PASS: test/tpm2-command_unit
PASS: test/tpm2-response_unit
PASS: test/tss2-tcti-tabrmd_unit
PASS: test/tcti-tabrmd-receive_unit
PASS: test/util_unit
============================================================================
Testsuite summary for tpm2-abrmd 2.2.0_rc0
============================================================================
# TOTAL: 49
# PASS:  48
# SKIP:  0
# XFAIL: 1
# FAIL:  0
# XPASS: 0
# ERROR: 0

**Comment by r4yv3n** [comment]
Problem solve. I tried to use the apt repo package tpm2-tools in combination with a compiled version of tpm2-abrmd and tpm2-pkcs11 which was a disaster. The fix was purging tpm2-tools and building it all from scratch.

Now it all works! Mostly!
