### ISSUE TITLE
Could not create RSA public key

### ISSUE THREAD

**Issue by timdesi** [tpm2-software/tpm2-pkcs11#341]
I am testing with Java 13, IBM TMP2 (1332) simulator and latest code from master brunch.

When try to use Cipher - RSA/ECB/NoPadding for Encryption PKCS11 provider try to use native C_CreateObject to generate public key and exit with error below. This function looks that is not implemented yet.

If you need further information or sample application let me know.

```

   java.security.InvalidKeyException: Could not create RSA public key
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSAKeyFactory.implTranslatePublicKey(P11RSAKeyFactory.java:71)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyFactory.engineTranslateKey(P11KeyFactory.java:127)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyFactory.convertKey(P11KeyFactory.java:64)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSACipher.implInit(P11RSACipher.java:200)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSACipher.engineInit(P11RSACipher.java:168)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1299)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1239)
	at javaapplication4.JavaApplication4.main(JavaApplication4.java:108)
  Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_FUNCTION_NOT_SUPPORTED
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSAKeyFactory.generatePublic(P11RSAKeyFactory.java:198)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSAKeyFactory.implTranslatePublicKey(P11RSAKeyFactory.java:57)
```

**Comment by williamcroberts** [comment]
Can you please provide sample code?

**Comment by timdesi** [comment]
Sample code and console output is below;

```

package tpm2;

import java.security.Key;
import static org.junit.jupiter.api.Assertions.*;

import java.security.KeyStore;
import java.security.Provider;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import javax.crypto.Cipher;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class PKCS11Test {

  @BeforeAll
  static void setUpBeforeClass() throws Exception {

    //	    String pkcs11Config = "name = SmartCard\nlibrary = /home/wcrobert/workspace/tpm2-pkcs11/src/.libs/libtpm2_pkcs11.so.0.0.0";
    //	    ByteArrayInputStream confStream = new ByteArrayInputStream(pkcs11Config.getBytes());
    //	    Provider prov = new sun.security.pkcs11.SunPKCS11(confStream);
    //	    Security.addProvider(prov);
    KeyStore keyStore = null;
    String pin = "myuserpin";
    try {
      keyStore = KeyStore.getInstance("PKCS11-TPM2");
      KeyStore.PasswordProtection pp = new KeyStore.PasswordProtection(pin.toCharArray());
      keyStore.load(null, pp.getPassword());

      System.out.println("KeyStore Type : " + keyStore.getType());
      System.out.println("KeyStore Size : " + keyStore.size());

      Provider prov = keyStore.getProvider();
      System.out.println("Provider Name : " + prov.getName());
      System.out.println("Provider Info : " + prov.getInfo());
      System.out.println("Provider Version : " + prov.getVersionStr());

      Enumeration<String> aliases = keyStore.aliases();
      while (aliases.hasMoreElements()) {
        String alias = aliases.nextElement();

        KeyStore.Entry obj = keyStore.getEntry(alias.toString(), null);
        try {
          //System.out.println(obj);
        } catch (Exception e) {
          e.printStackTrace();
          continue;
        }
      }

      //List Provider Services
      System.out.println("\n-- Provider Services --\n");

      ArrayList list = new ArrayList();
      for (Provider.Service service : prov.getServices()) {
        if (service.getType().equals("Cipher")) {
          String info = service.getType() + " - " + service.getAlgorithm();
          list.add(info);

        }
      }

      Collections.sort(list);

      list.forEach((n) -> System.out.println(n));

      //Cipher Encode/Decode

      Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding", prov);
      System.out.println("Cipher Provider : " + cipher.getProvider());

      byte[] plainData = "mysecretdata".getBytes("UTF-8");

      String keyalias = "rsakey1";

      Key rsakey1 = keyStore.getKey(keyalias, null);
      System.out.println("Key Algorithm : " + rsakey1.getAlgorithm());

      X509Certificate certificate = (X509Certificate) keyStore.getCertificate(keyalias);
      Key publicKey1 = certificate.getPublicKey();

      if (rsakey1.getAlgorithm().equals("RSA")) {
        cipher.init(Cipher.ENCRYPT_MODE, publicKey1);
        byte[] encryptedData = cipher.doFinal(plainData);

        cipher.init(Cipher.DECRYPT_MODE, rsakey1);
        int output = cipher.getOutputSize(encryptedData.length);
        byte[] decryptedData = cipher.doFinal(encryptedData);

        System.out.println("DecryptedData : " + new String(decryptedData, output - plainData.length, plainData.length));

      }

    } catch (Exception e) {
      System.out.println(e);
      e.printStackTrace();
    }

  }

  @Test
  void test() {
    fail("Not yet implemented");
  }

}

```

```
KeyStore Type : PKCS11-TPM2
KeyStore Size : 2
Provider Name : SunPKCS11-TPM2
Provider Info : SunPKCS11-TPM2 using library /usr/lib64/pkcs11/libtpm2_pkcs11.so
Provider Version : 13

-- Provider Services --

Cipher - AES/CBC/NoPadding
Cipher - AES/CBC/PKCS5Padding
Cipher - AES_128/CBC/NoPadding
Cipher - AES_192/CBC/NoPadding
Cipher - AES_256/CBC/NoPadding
Cipher - RSA/ECB/NoPadding
Cipher - RSA/ECB/PKCS1Padding
Cipher Provider : SunPKCS11-TPM2 version 13
Key Algorithm : RSA
java.security.InvalidKeyException: Could not create RSA public key
java.security.InvalidKeyException: Could not create RSA public key
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSAKeyFactory.implTranslatePublicKey(P11RSAKeyFactory.java:71)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyFactory.engineTranslateKey(P11KeyFactory.java:127)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyFactory.convertKey(P11KeyFactory.java:64)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSACipher.implInit(P11RSACipher.java:200)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSACipher.engineInit(P11RSACipher.java:168)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1299)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1239)
	at tpm2.PKCS11Test.setUpBeforeClass(JavaApplication5.java:86)
	at tpm2.NewMain.main(NewMain.java:18)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_FUNCTION_NOT_SUPPORTED
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSAKeyFactory.generatePublic(P11RSAKeyFactory.java:198)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11RSAKeyFactory.implTranslatePublicKey(P11RSAKeyFactory.java:57)
	... 8 more
BUILD SUCCESSFUL (total time: 1 second)
```

**Comment by williamcroberts** [comment]
The reason this fails is that they are calling C_CreateObject(). Looks like they are trying to create a public key object from the certificate rather than using the one that's already there or just breaking all the parts out of the certificate.

**Comment by williamcroberts** [comment]
I'm taking this off the 1.0 milestone, this can be a feature that we can add in the future without having to deal with backwards compat issues.

**Comment by williamcroberts** [comment]
I need to figure out how to build java in auto-tools and add it to test framework as well.

**Comment by williamcroberts** [comment]
http://freesoftwaremagazine.com/articles/autotools_example/

**Comment by williamcroberts** [comment]
FYI I have this work started on: https://github.com/williamcroberts/tpm2-pkcs11/tree/java-pkcs-tests

**Comment by timdesi** [comment]
Thx. @williamcroberts, now i could verify that basic RSA Encrypt/Decrypt works.

```
-- RSA Cipher --

Cipher Provider : SunPKCS11-TPM2 version 13
PlainData : mysecretdata (6d7973656372657464617461)
Key1 Algorithm : RSA
EncryptedData : 76680f75a8c3ac1603c8c9ab9b308cc7547ac769494303e13e73742039c92ed582908ceacda90f21dec1ff86e40f86798110c3e3d55d15ecd0d93c4ff4a787cb27a2d36f34fb720cb5846f9d43e2c0fe0194d6cef249b2ec971196f1758a6efef3827d5f52164b1196f34bb4454a1ebf037e2f0d27f03496b448e6a932134614
DecryptedData : mysecretdata
```
