### ISSUE TITLE
CKR_ATTRIBUTE_TYPE_INVALID while trying to get RSA private key

### ISSUE THREAD

**Issue by timdesi** [tpm2-software/tpm2-pkcs11#347]
I am trying to get RSA Private Key from keystore with #344 latest commit but application exit with CKR_ATTRIBUTE_TYPE_INVALID exception. This was working previously.

If you need extra debug information let me know.

```
-- RSA Cipher --

Cipher Provider : SunPKCS11-TPM2 version 13
PlainData : 6d7973656372657464617461

sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_TYPE_INVALID
java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_TYPE_INVALID
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Key.getAttributes(P11Key.java:310)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Key.privateKey(P11Key.java:365)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.loadPkey(P11KeyStore.java:1327)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineGetKey(P11KeyStore.java:314)
	at java.base/java.security.KeyStore.getKey(KeyStore.java:1050)
	at javaapplication4.JavaApplication4.main(JavaApplication4.java:100)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_TYPE_INVALID
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_GetAttributeValue(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Key.getAttributes(P11Key.java:308)
	... 5 more
```

![Screenshot from 2019-12-09 11-40-20](https://user-images.githubusercontent.com/36303267/70436276-90caa080-1a91-11ea-837e-46fb09d54cc3.png)

![Screenshot from 2019-12-09 11-41-06](https://user-images.githubusercontent.com/36303267/70436314-a63fca80-1a91-11ea-9d2c-e3433b6401a9.png)

**Comment by williamcroberts** [comment]
I was able to reproduce and add a log statement:
INFO on line: "404" in file: "src/lib/object.c": Invalid Attribute: type(259) ulValueLen(18446744073709551615), pData(null)

**Comment by williamcroberts** [comment]
Looks like I forgot to add CKA_SENSITIVE attribute to all private key objects, fix in progress.

**Comment by williamcroberts** [comment]
Working with code:
```java
package tpm2;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;
import java.security.KeyStore;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.KeyStore.SecretKeyEntry;
import java.security.KeyStore.TrustedCertificateEntry;
import java.security.Provider;
import java.security.Security;
import java.security.cert.X509Certificate;
import java.util.Enumeration;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class PKCS11Test {

	@BeforeAll
	static void setUpBeforeClass() throws Exception {
		
	    String pkcs11Config = "name = SmartCard\nlibrary = /home/wcrobert/workspace/tpm2-pkcs11/src/.libs/libtpm2_pkcs11.so.0.0.0";
	    ByteArrayInputStream confStream = new ByteArrayInputStream(pkcs11Config.getBytes());
	    Provider prov = new sun.security.pkcs11.SunPKCS11(confStream);
	    Security.addProvider(prov);
	    KeyStore keyStore = null;
	    String pin = "myuserpin";
	    try {
	        keyStore = KeyStore.getInstance("PKCS11",prov);
	        KeyStore.PasswordProtection pp = new KeyStore.PasswordProtection(pin.toCharArray());
	        keyStore.load(null ,  pp.getPassword());
	        
        
	        Enumeration<String> aliases = keyStore.aliases();
	        while (aliases.hasMoreElements()) {
	            String alias = aliases.nextElement();
	            
	            KeyStore.Entry obj = keyStore.getEntry(alias.toString(), null);
	            try {
	                System.out.println(obj);
	            } catch (Exception e) {
	    	        e.printStackTrace();
	            	continue;
	            }
	        }
	    } catch (Exception e) {
	    	System.out.println(e);
	        e.printStackTrace();
	    }
		
	}

	@Test
	void test() {
		fail("Not yet implemented");
	}

}
```
