### ISSUE TITLE
tpm2_ptool.py init: support existing primary object

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#35]
Support an existing primary object via a `-p|--primary=<handle>` option. Allow the `<handle>` to be optional and default to `0x81000001` as what is discussed in https://github.com/tpm2-software/tpm2-pkcs11/pull/30.

**Comment by dwmw2** [comment]
I've been using persistent objects 0x81000000 and 0x81000001 for engine testing, now I let tpm2_ptool.py create 0x81000002 for me for the token.

I thought you said you only created one. But I still get...
```
$ ./tpm2_ptool.py addkey --algorithm=rsa2048 --label=label --userpin=myuserpin
Traceback (most recent call last):
  File "./tpm2_ptool.py", line 1283, in <module>
    main()
  File "./tpm2_ptool.py", line 1280, in main
    commandlet.get()[which](d)
  File "./tpm2_ptool.py", line 996, in __call__
    sealctx = tpm2.load(pobj['handle'], pinpobjauth, sealpriv, sealpub)
  File "./tpm2_ptool.py", line 175, in load
    raise RuntimeError("Could not execute tpm2_load: %s", stderr)
RuntimeError: ('Could not execute tpm2_load: %s', 'ERROR: Tss2_Sys_Load(0x902) - tpm:warn(2.0): out of memory for object contexts\nERROR: Unable to run tpm2_load\n')
```

I then deleted my 0x81000000 key and still get the above. What am I missing here?

**Comment by dwmw2** [comment]
I rebooted (well, hibernated) and the TPM started working again. Then I got:
```
$ ./tpm2_ptool.py addkey --algorithm=rsa2048 --label=label --userpin=myuserpin
Traceback (most recent call last):
  File "./tpm2_ptool.py", line 1283, in <module>
    main()
  File "./tpm2_ptool.py", line 1280, in main
    commandlet.get()[which](d)
  File "./tpm2_ptool.py", line 1043, in __call__
    tertiarypriv, tertiarypub, tertiarypubdata = tpm2.create(sobjctx, sobjauth, objauth, alg=alg)
  File "./tpm2_ptool.py", line 244, in create
    raise RuntimeError("Could not execute tpm2_create: %s" % str(stderr))
RuntimeError: Could not execute tpm2_create: ERROR: Tss2_Sys_Create(0x18A) - tpm:handle(1):the type of the value is not appropriate for the use
ERROR: Unable to run tpm2_create
```
... and now it's back to the same 0x902 error as above.
