### ISSUE TITLE
Problems with python tools at init and backup db

### ISSUE THREAD

**Issue by timdesi** [tpm2-software/tpm2-pkcs11#379]
With latest source code i have error below when run **tpm2_ptool init** command.

python --version
Python 3.8.0

```
 ./tpm2_ptool init
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
    main()
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/command.py", line 85, in init
    commandlet.get()[d['which']](d)
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 77, in __call__
    db.create()
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/db.py", line 421, in create
    self._do_create()
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/db.py", line 408, in _do_create
    c.execute(s)
sqlite3.OperationalError: unrecognized token: "0x00FFFFFF"

```
```

./tpm2_ptool init
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
    main()
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/command.py", line 85, in init
    commandlet.get()[d['which']](d)
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 77, in __call__
    db.create()
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/db.py", line 420, in create
    dbbakpath = self.backup()
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/db.py", line 234, in backup
    raise RuntimeError("Backup DB exists at {} not overwriting. "
RuntimeError: Backup DB exists at /home/desi/.tpm2_pkcs11/tpm2_pkcs11.sqlite3.bak not overwriting. Refusing to run

```

**Comment by williamcroberts** [comment]
Weird, does this patch fix your issue:
```diff
diff --git a/tools/tpm2_pkcs11/db.py b/tools/tpm2_pkcs11/db.py
index 9b2ff77537e9..beaad7959119 100644
--- a/tools/tpm2_pkcs11/db.py
+++ b/tools/tpm2_pkcs11/db.py
@@ -396,9 +396,9 @@ class Db(object):
                 BEFORE INSERT ON tobjects
                 BEGIN
                     SELECT CASE WHEN
-                        (SELECT COUNT (*) FROM tobjects) >= 0x00FFFFFF
+                        (SELECT COUNT (*) FROM tobjects) >= 16777215
                     THEN
-                        RAISE(FAIL, "Maximum object count of 0xFFFFFFFF reached.")
+                        RAISE(FAIL, "Maximum object count of 16777215 reached.")
                     END;
                 END;
             '''),
```

**Comment by timdesi** [comment]
Thx. @williamcroberts  patch works and db is created. Token, Private and public keys are created. 

Unfortunately while trying to generate ssl certificate with openssl engine i have similar errors. 

```
OPENSSL_CONF=/prgs/tpm2_test1/tpm2-pkcs11.openssl.conf openssl req -new -x509 -days 365 -subj '/CN=rsakey1/' -sha256 -engine pkcs11 -keyform engine -key slot_1-label_rsakey1 -out rsakey1cert.pem
ERROR: unrecognized token: "0x00FFFFFF"
ERROR: db creation failed
Unable to load module /usr/lib64/pkcs11/libtpm2_pkcs11.so
can't use that engine
139998161409936:error:82065005:PKCS#11 module:pkcs11_check_token:General Error:p11_load.c:92:
139998161409936:error:260B806D:engine routines:ENGINE_TABLE_REGISTER:init failed:eng_table.c:175:
no engine specified
unable to load Private Key

```

```
$ ./tpm2_ptool listobjects --label token1
- CKA_CLASS: CKO_PRIVATE_KEY
  CKA_ID: '31'
  CKA_KEY_TYPE: CKK_RSA
  CKA_LABEL: rsakey1
  id: 1
- CKA_CLASS: CKO_PUBLIC_KEY
  CKA_ID: '31'
  CKA_KEY_TYPE: CKK_RSA
  CKA_LABEL: rsakey1
  id: 2
- CKA_CLASS: CKO_PRIVATE_KEY
  CKA_ID: '32'
  CKA_KEY_TYPE: CKK_RSA
  CKA_LABEL: rsakey2
  id: 3
- CKA_CLASS: CKO_PUBLIC_KEY
  CKA_ID: '32'
  CKA_KEY_TYPE: CKK_RSA
  CKA_LABEL: rsakey2
  id: 4
- CKA_CLASS: CKO_SECRET_KEY
  CKA_ID: '33'
  CKA_KEY_TYPE: CKK_AES
  CKA_LABEL: aeskey3
  id: 5
- CKA_CLASS: CKO_SECRET_KEY
  CKA_ID: '34'
  CKA_KEY_TYPE: CKK_AES
  CKA_LABEL: aeskey4
  id: 6
- CKA_CLASS: CKO_PRIVATE_KEY
  CKA_ID: '35'
  CKA_KEY_TYPE: CKK_EC
  CKA_LABEL: ecckey5
  id: 7
- CKA_CLASS: CKO_PUBLIC_KEY
  CKA_ID: '35'
  CKA_KEY_TYPE: CKK_EC
  CKA_LABEL: ecckey5
  id: 8
- CKA_CLASS: CKO_PRIVATE_KEY
  CKA_ID: '36'
  CKA_KEY_TYPE: CKK_EC
  CKA_LABEL: ecckey6
  id: 9
- CKA_CLASS: CKO_PUBLIC_KEY
  CKA_ID: '36'
  CKA_KEY_TYPE: CKK_EC
  CKA_LABEL: ecckey6
  id: 10

```

**Comment by williamcroberts** [comment]
Add this patch:
```diff
diff --git a/src/lib/db.c b/src/lib/db.c
index 481fec1a798b..2b8d02712a42 100644
--- a/src/lib/db.c
+++ b/src/lib/db.c
@@ -1565,9 +1565,9 @@ CK_RV db_setup(sqlite3 *db, const char *path) {
         "BEFORE INSERT ON tobjects\n"
         "BEGIN\n"
         "    SELECT CASE WHEN\n"
-        "        (SELECT COUNT (*) FROM tobjects) >= 0x00FFFFFF\n"
+        "        (SELECT COUNT (*) FROM tobjects) >= 16777215\n"
         "    THEN\n"
-        "        RAISE(FAIL, \"Maximum object count of 0x00FFFFFF reached.\")\n"
+        "        RAISE(FAIL, \"Maximum object count of 16777215 reached.\")\n"
         "    END;\n"
         "END;\n"
     };
```

**Comment by timdesi** [comment]
Thx. now works.

**Comment by williamcroberts** [comment]
Reopen, I need to apply these patches and merge them.
