### ISSUE TITLE
pkcs11-tool: Deleting the public key after deleting the private key causes segfault

### ISSUE THREAD

**Issue by cplappert** [tpm2-software/tpm2-pkcs11#399]
The deletion of the public key causes a segfault (l.11) if the private key was deleted before.
Only deleting the private key is not enough the delete the object (l.10).

```
01: export mod_path=PATH_TO_LIBTPM2_PKCS11.so
02: export TPM2_PKCS11_STORE="$HOME/store"
03: alias pkcs11_tool='pkcs11-tool --module $mod_path'
04: mkdir $TPM2_PKCS11_STORE

05: pkcs11_tool --init-token --slot=1 --label=myfirsttoken --so-pin=myfirstsopin
06: pkcs11_tool --init-pin --slot=1 --login --login-type="so" --so-pin=myfirstsopin --pin=myfirstuserpin
07: pkcs11_tool --keypairgen --slot=1 --label="mysignkey" --login --pin=myfirstuserpin 
08: pkcs11_tool --list-objects --slot=1

09: pkcs11_tool --delete-object --slot=1 --label="mysignkey" --pin=myfirstuserpin --login --type=privkey
10: pkcs11_tool --list-objects --slot=1

11: pkcs11_tool --delete-object --slot=1 --label="mysignkey" --pin=myfirstuserpin --login --type=pubkey
12: pkcs11_tool --list-objects --slot=1
```

**Comment by williamcroberts** [comment]
Interesting, this repro's on the CI, but not locally. @cplappert the CI is using OpenSC package version 0.15.0 (as packaged in Ubuntu 16.04). What version are you using?

Looking at the stack trace, its nonsense, looks like something is really going wrong. Can you try
running against OpenSC version 0.17?

```bash
git clone https://github.com/OpenSC/OpenSC.git
git checkout 0.17.0
./bootstrap
# for debug symbols in so
./configure --disable-optimization 
make -j4
```
use the command for your testing:
OpenSC/src/tools/.libs/pkcs11-tool

CI Output w/ASAN:
```
==13448==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f5ae32071c4 bp 0x7ffdf9130260 sp 0x7ffdf9130210 T0)
==13448==The signal is caused by a READ memory access.
==13448==Hint: address points to the zero page.
    #0 0x7f5ae32071c3 in session_ctx_logout /workspace/tpm2-pkcs11/build/../src/lib/session_ctx.c:374:24
    #1 0x7f5ae3207b2c in session_table_free_ctx_by_ctx /workspace/tpm2-pkcs11/build/../src/lib/session_table.c:116:14
    #2 0x7f5ae3206060 in session_close /workspace/tpm2-pkcs11/build/../src/lib/session.c:107:12
    #3 0x7f5ae31e7d03 in C_CloseSession /workspace/tpm2-pkcs11/build/../src/pkcs11.c:431:5
    #4 0x4047d5 in i2d_X509_NAME (/usr/bin/pkcs11-tool+0x4047d5)
    #5 0x7f5ae647f82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x406348 in i2d_X509_NAME (/usr/bin/pkcs11-tool+0x406348)
```
