### ISSUE TITLE
Error while running p11tool and tpm2_ptool on Fedora 31

### ISSUE THREAD

**Issue by stefanberger** [tpm2-software/tpm2-pkcs11#479]
I am running into the following issue here on Fedora 31 with the following packages:

```
> rpm -q -a  | grep tpm2
tpm2-pkcs11-tools-1.0.1-1.fc31.x86_64
tpm2-abrmd-devel-2.3.1-1.fc31.x86_64
tpm2-tss-devel-2.3.1-1.fc31.x86_64
tpm2-pkcs11-1.0.1-1.fc31.x86_64
tpm2-abrmd-selinux-2.3.1-2.fc31.noarch
tpm2-tools-4.0.1-1.fc31.x86_64
tpm2-abrmd-2.3.1-1.fc31.x86_64
tpm2-tss-2.3.1-1.fc31.x86_64
```

```
> tpm2_ptool destroy --pid 1
This will delete the primary object of id "1" and all associated data from db under "/root" [y/N] y
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/usr/lib/python3.7/site-packages/tpm2_pkcs11/command.py", line 85, in init
    commandlet.get()[d['which']](d)
  File "/usr/lib/python3.7/site-packages/tpm2_pkcs11/commandlets_store.py", line 176, in __call__
    tpm2.evictcontrol(ownerauth, tr_file)
  File "/usr/lib/python3.7/site-packages/tpm2_pkcs11/tpm2.py", line 49, in evictcontrol
    stderr)
RuntimeError: ('Could not execute tpm2_evictcontrol: %s', b'ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Device or resource busy \nWARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f906dd8cfc0 failed with a000a \nWARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device \nERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so \n')
```

Obviously it tries to use the wrong interface...
When I now run it using this command line here it with the env variable `TPM2TOOLS_TCTI set` it seems to work:

```
[root@localhost ~]# TPM2TOOLS_TCTI=tabrmd: tpm2_ptool destroy --pid 1
This will delete the primary object of id "1" and all associated data from db under "/root" [y/N] y
Primary Object id "1"not found
```

Should I have to pass this environment variable? The following example seems to indicate that if this environment variable needs to be set it should be set in the python tool or a config file because p11tool doesn't seem to pass it all the way through. (Not setting the environment variable leads to the same result.)

```
> tpm2_ptool init
action: Created
id: 3
> tpm2_ptool addtoken --label label3 --pid 3 --sopin mypin --userpin mypin
> tpm2_ptool addkey --key-label keylabel --label label3 --algorithm rsa2048 --sopin mypin
action: add
private:
  CKA_ID: '30623838306439643430316164393434'
public:
  CKA_ID: '30623838306439643430316164393434'
> p11tool --list-tokens
[...]
Token 3:
        URL: pkcs11:model=SW%20%20%20TPM;manufacturer=IBM;serial=0000000000000000;token=label3
        Label: label3
        Type: Hardware token
        Flags: RNG, Requires login
        Manufacturer: IBM
        Model: SW   TPM
        Serial: 0000000000000000
        Module: libtpm2_pkcs11.so
> TPM2TOOLS_TCTI="tabrmd:" p11tool --list-keys 'pkcs11:model=SW%20%20%20TPM;manufacturer=IBM;serial=0000000000000000;token=label3'
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Device or resource busy
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f47813f9fc0 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Device or resource busy
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f4780663fc0 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so
No matching objects found
```

**Comment by dnoliver** [comment]
Hi @stefanberger,

I believe you don't need tpm2-abrmd on Fedora 31 (at least for kernels > 4.18). There is an in-kernel resource manager in `/dev/tpmrm0` that works out of the box (at least for me).

Usually, this sets my device correctly:

```
export TPM2TOOLS_TCTI="device:/dev/tpmrm0"
export TPM2_PKCS11_TCTI="device:/dev/tpmrm0"
```

Also, I am not sure if `tpm2_ptool` reacts to `TPM2TOOLS_TCTI` or `TPM2_PKCS11_TCTI`.

**Comment by stefanberger** [comment]
@dnoliver Thanks. I did not know this environment variable. It helps a bit but for some reason it cannot find the created key when using the `p11tool`:

```
[root@localhost ~]# tpm2_ptool init
action: Created
id: 1

[root@localhost ~]# tpm2_ptool addtoken --label label1 --pid 1 --sopin mypin --userpin mypin
[root@localhost ~]# tpm2_ptool addkey --key-label keylabel --label label1 --algorithm rsa2048 --sopin mypin
action: add
private:
  CKA_ID: '35353964343231303964636636356233'
public:
  CKA_ID: '35353964343231303964636636356233'
[root@localhost ~]# p11tool --list-tokens
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Device or resource busy
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f3fff8f5fc0 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so
Token 0:
        URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
        Label: System Trust
        Type: Trust module
        Flags: uPIN uninitialized
        Manufacturer: PKCS#11 Kit
        Model: p11-kit-trust
        Serial: 1
        Module: p11-kit-trust.so


Token 1:
        URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
        Label: Default Trust
        Type: Trust module
        Flags: uPIN uninitialized
        Manufacturer: PKCS#11 Kit
        Model: p11-kit-trust
        Serial: 1
        Module: p11-kit-trust.so


Token 2:
        URL: pkcs11:model=SW%20%20%20TPM;manufacturer=IBM;serial=0000000000000000;token=label1
        Label: label1
        Type: Hardware token
        Flags: RNG, Requires login
        Manufacturer: IBM
        Model: SW   TPM
        Serial: 0000000000000000
        Module: libtpm2_pkcs11.so


[root@localhost ~]# TPM2_PKCS11_TCTI="device:/dev/tpmrm0" p11tool --list-keys 'pkcs11:model=SW%20%20%20TPM;manufacturer=IBM;serial=0000000000000000;token=label1'
No matching objects found
[root@localhost ~]# tpm2_ptool listobjects --label label1
- CKA_CLASS: CKO_PRIVATE_KEY
  CKA_ID: '35353964343231303964636636356233'
  CKA_KEY_TYPE: CKK_RSA
  CKA_LABEL: keylabel
  id: 1
- CKA_CLASS: CKO_PUBLIC_KEY
  CKA_ID: '35353964343231303964636636356233'
  CKA_KEY_TYPE: CKK_RSA
  CKA_LABEL: keylabel
  id: 2
```

**Comment by dnoliver** [comment]
This is how I do it (with tpm2-pkcs11 1.2.0 on Fedora 32):

```bash
mkdir -p /etc/tpm2_pkcs11

export TPM2TOOLS_TCTI="device:/dev/tpmrm0"
export TPM2_PKCS11_TCTI="device:/dev/tpmrm0"

tpm2_ptool init
tpm2_ptool addtoken \
    --pid=1 \
    --sopin=sopin \
    --userpin=userpin \
    --label=label
tpm2_ptool addkey \
    --algorithm=rsa2048 \
    --label=label \
    --userpin=userpin
tpm2_ptool config \
    --key tcti \
    --value "device:/dev/tpmrm0" \
    --label label
TOKEN=`p11tool --list-token-urls | grep "token=label"`
export GNUTLS_PIN=userpin
export GNUTLS_SO_PIN=sopin
p11tool --login --list-all "${TOKEN}" --outfile p11tool.out
```

I do 2 calls to get the private key URI, the second one requires PIN, which is passed with `GNUTLS_PIN` and `GNUTLS_SO_PIN` env vars.

Sometimes it helps specifying the directory where you store is located

```sh
export TPM2_PKCS11_STORE=/etc/tpm2_pkcs11
```

**Comment by stefanberger** [comment]
@dnoliver Thanks. This helped a lot!!

**Comment by stefanberger** [comment]
I am now using this here in my script:

```
(tpm2_ptool config \
                                --key tcti \
                                --value "tabrmd" \
                                --label "${label}"
```
It allows for non-root users as well since access to /dev/tpmrm0 (typically) requires root.
I did not know this 'config' command, which seems key here. Maybe 'tabrmd' should be the default value for the tcti key that is set even if one does nothing?
