### ISSUE TITLE
make check fails pyasn1.type.error.ValueConstraintError

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#653]
When I try to run make check on my rasbian system, I get the following error (for all tests)

```
engine "pkcs11" set.
p11_pkey.c:528 pkcs11_try_pkey_ec_sign() not implemented
engine "pkcs11" set.
Adding EC Certificate
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 297, in _testValue
    raise error.ValueConstraintError(value)
pyasn1.type.error.ValueConstraintError: Extensions:
```

Full Log:
```
--tabrmd-tcti=swtpm
--tsetup-script=./test/integration/scripts/create_pkcs_store.sh
./test/integration/pkcs-login-logout.int
Starting simulator on port 13170
starting daemon: /usr/bin/swtpm
  environment: 
  options: socket --tpm2 --server port=13170                              --ctrl type=tcp,port=13171                              --flags not-need-init --tpmstate dir=/tmp/tpm_simulator_U8ARmC
successfully started daemon: /usr/bin/swtpm with PID: 19755
/home/pi/tpm2-pkcs11
simulator PID: 19755
Simulator with PID 19755 bound to port 13170 and  13171 successfully.
starting daemon: /usr/local/sbin/tpm2-abrmd
  environment: G_MESSAGES_DEBUG=all
  options: --session --dbus-name=com.intel.tss2.Tabrmd13170 --tcti=swtpm:port=13170
successfully started daemon: /usr/local/sbin/tpm2-abrmd with PID: 19766
tabrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd13170
tabrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd13170
Run setup script ./test/integration/scripts/create_pkcs_store.sh
source /home/pi/tpm2-pkcs11/test/integration/scripts/helpers.sh
SETUP SCRIPT - DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-OYYg1jaWec,guid=d478a98a2e3002bb4f71a635602a2aae
SETUP SCRIPT - TPM2TOOLS_TCTI: tabrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd13170
SETUP SCRIPT - PYTHONPATH: /home/pi/tpm2-pkcs11/tools
--tmpdir=/tmp/tpm_simulator_U8ARmC
action: Created
id: 1

one
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: a030d6bff42318eb3c596722c1c72df0008c112d29535e09decf84cbffff610ce-tabrmd-tcti=swtpm
--tsetup-script=./test/integration/scripts/create_pkcs_store.sh
./test/integration/pkcs-login-logout.int
Starting simulator on port 13170
starting daemon: /usr/bin/swtpm
  environment: 
  options: socket --tpm2 --server port=13170                              --ctrl type=tcp,port=13171                              --flags not-need-init --tpmstate dir=/tmp/tpm_simulator_U8ARmC
successfully started daemon: /usr/bin/swtpm with PID: 19755
/home/pi/tpm2-pkcs11
simulator PID: 19755
Simulator with PID 19755 bound to port 13170 and  13171 successfully.
starting daemon: /usr/local/sbin/tpm2-abrmd
  environment: G_MESSAGES_DEBUG=all
  options: --session --dbus-name=com.intel.tss2.Tabrmd13170 --tcti=swtpm:port=13170
successfully started daemon: /usr/local/sbin/tpm2-abrmd with PID: 19766
tabrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd13170
tabrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd13170
Run setup script ./test/integration/scripts/create_pkcs_store.sh
source /home/pi/tpm2-pkcs11/test/integration/scripts/helpers.sh
SETUP SCRIPT - DBUS_SESSION_BUS_ADDRESS: unix:abstract=/tmp/dbus-OYYg1jaWec,guid=d478a98a2e3002bb4f71a635602a2aae
SETUP SCRIPT - TPM2TOOLS_TCTI: tabrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd13170
SETUP SCRIPT - PYTHONPATH: /home/pi/tpm2-pkcs11/tools
--tmpdir=/tmp/tpm_simulator_U8ARmC
action: Created
id: 1

one
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: a030d6bff42318eb3c596722c1c72df0008c112d29535e09decf84cbffff610ceecee132da292b3cfb2f0b78ea02fbd578a4e0e1cd658f75417f6c61baa1d7ba0bd0e6b951ffb148153c8129a44d5cce8a009afbb22542109363ad3500d27dcbe8a4cda2cf6d12db54d280b6b47dc50a45e0c6b25239c8bb27400ed50834ca4e00814109cbbac817f347cbc38db5a16ef46ac87898cae33694254353fa58abd24ee58b62e21c09afc362cd521bada42ff4d24f57c5f351f595019d479ef47c7cd66a6ba0086cc7e898a1da77c8ea921ceafc765ec0aa0822cc839a369c8ba364147889a0d575e06bdd7533b511216913b0b194b57720e523d513b70a1c26e53f
2
tpm2_ptool init --primary-auth=anotherpobjpin --primary-handle=0x81000002 --primary-auth=foopass --path=/tmp/tpm_simulator_U8ARmC
action: Added
id: 2

3
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: a030d6bff42318eb3c596722c1c72df0008c112d29535e09decf84cbffff610ceecee132da292b3cfb2f0b78ea02fbd578a4e0e1cd658f75417f6c61baa1d7ba0bd0e6b951ffb148153c8129a44d5cce8a009afbb22542109363ad3500d27dcbe8a4cda2cf6d12db54d280b6b47dc50a45e0c6b25239c8bb27400ed50834ca4e00814109cbbac817f347cbc38db5a16ef46ac87898cae33694254353fa58abd24ee58b62e21c09afc362cd521bada42ff4d24f57c5f351f595019d479ef47c7cd66a6ba0086cc7e898a1da77c8ea921ceafc765ec0aa0822cc839a369c8ba364147889a0d575e06bdd7533b511216913b0b194b57720e523d513b70a1c26e53f
persistent-handle: 0x81000003
action: persisted
tpm2_ptool init --primary-handle=/tmp/tpm_simulator_U8ARmC/primary3.handle --path=/tmp/tpm_simulator_U8ARmC
action: Added
id: 3

config:
  pss-sigs-good: false
  token-init: true
label: label
objects: []
pin:
  so:
    seal-auth: 19ada56c76bd583d619aef56a828f4fc
  user:
    seal-auth: 1ea7f0164fc6e130158837a79d0e70e0
wrappingkey:
  auth: 1ea7f0164fc6e130158837a79d0e70e0
  hex: '66616434666339363739323264613635643261373735636337346639643335656536303430616164363038363231333837313935393330646138313865323433'
  soauth: 19ada56c76bd583d619aef56a828f4fc

config:
  pss-sigs-good: false
  token-init: true
label: label
objects: []
pin:
  so:
    seal-auth: 19ada56c76bd583d619aef56a828f4fc
  user:
    seal-auth: d4e2ba77c761041603c3582fe9a3ebe8
wrappingkey:
  auth: d4e2ba77c761041603c3582fe9a3ebe8
  hex: '66616434666339363739323264613635643261373735636337346639643335656536303430616164363038363231333837313935393330646138313865323433'
  soauth: 19ada56c76bd583d619aef56a828f4fc

Adding 3 AES 256 keys under token "label"
ecee132da292b3cfb2f0b78ea02fbd578a4e0e1cd658f75417f6c61baa1d7ba0bd0e6b951ffb148153c8129a44d5cce8a009afbb22542109363ad3500d27dcbe8a4cda2cf6d12db54d280b6b47dc50a45e0c6b25239c8bb27400ed50834ca4e00814109cbbac817f347cbc38db5a16ef46ac87898cae33694254353fa58abd24ee58b62e21c09afc362cd521bada42ff4d24f57c5f351f595019d479ef47c7cd66a6ba0086cc7e898a1da77c8ea921ceafc765ec0aa0822cc839a369c8ba364147889a0d575e06bdd7533b511216913b0b194b57720e523d513b70a1c26e53f
2
tpm2_ptool init --primary-auth=anotherpobjpin --primary-handle=0x81000002 --primary-auth=foopass --path=/tmp/tpm_simulator_U8ARmC
action: Added
id: 2

3
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: a030d6bff42318eb3c596722c1c72df0008c112d29535e09decf84cbffff610ceecee132da292b3cfb2f0b78ea02fbd578a4e0e1cd658f75417f6c61baa1d7ba0bd0e6b951ffb148153c8129a44d5cce8a009afbb22542109363ad3500d27dcbe8a4cda2cf6d12db54d280b6b47dc50a45e0c6b25239c8bb27400ed50834ca4e00814109cbbac817f347cbc38db5a16ef46ac87898cae33694254353fa58abd24ee58b62e21c09afc362cd521bada42ff4d24f57c5f351f595019d479ef47c7cd66a6ba0086cc7e898a1da77c8ea921ceafc765ec0aa0822cc839a369c8ba364147889a0d575e06bdd7533b511216913b0b194b57720e523d513b70a1c26e53f
persistent-handle: 0x81000003
action: persisted
tpm2_ptool init --primary-handle=/tmp/tpm_simulator_U8ARmC/primary3.handle --path=/tmp/tpm_simulator_U8ARmC
action: Added
id: 4

config:
  pss-sigs-good: false
  token-init: true
label: label
objects: []
pin:
  so:
    seal-auth: 19ada56c76bd583d619aef56a828f4fc
  user:
    seal-auth: 1ea7f0164fc6e130158837a79d0e70e0
wrappingkey:
  auth: 1ea7f0164fc6e130158837a79d0e70e0
  hex: '66616434666339363739323264613635643261373735636337346639643335656536303430616164363038363231333837313935393330646138313865323433'
  soauth: 19ada56c76bd583d619aef56a828f4fc

config:
  pss-sigs-good: false
  token-init: true
label: label
objects: []
pin:
  so:
    seal-auth: 19ada56c76bd583d619aef56a828f4fc
  user:
    seal-auth: d4e2ba77c761041603c3582fe9a3ebe8
wrappingkey:
  auth: d4e2ba77c761041603c3582fe9a3ebe8
  hex: '66616434666339363739323264613635643261373735636337346639643335656536303430616164363038363231333837313935393330646138313865323433'
  soauth: 19ada56c76bd583d619aef56a828f4fc

Adding 3 AES 256 keys under token "label"
action: add
private:
  CKA_ID: '34346334663364313363313736346162'
action: add
private:
  CKA_ID: '61306539633463393238343065393666'
action: add
private:
  CKA_ID: '38363363383837336533356434333630'
Added AES Keys
Adding 3 RSA 2048 keys under token "label"
action: add
private:
  CKA_ID: '32326533666336613730663964323437'
public:
  CKA_ID: '32326533666336613730663964323437'
action: add
private:
  CKA_ID: '36333966346636666665313438336230'
public:
  CKA_ID: '36333966346636666665313438336230'
action: add
private:
  CKA_ID: '36393066323461386430356335303963'
public:
  CKA_ID: '36393066323461386430356335303963'
Added RSA Keys
Adding 2 EC p256 keys under token "label"
action: add
private:
  CKA_ID: '37623336363664323734623161623938'
public:
  CKA_ID: '37623336363664323734623161623938'
action: add
private:
  CKA_ID: '38333062333336353362646238303264'
public:
  CKA_ID: '38333062333336353362646238303264'
Added EC Keys
Adding 1 x509 Certificate under token "label"
config:
  pss-sigs-good: false
  token-init: true
label: label
objects:
- 'auth: ': 22d903a4be7aab6ff2dde4d9de55446f
  encauth: 85ada30e8abfd52e7b4d0096:8f14576042a442b5b492ba2a1ed3a56e:c27ac4f5c0e5000b2d45ba7e43e9cbd6d6b2767657674f3b6680262eb80c59c6
  'id: ': 1
- 'auth: ': 5becce11f7c345e8c5b04ca8cde4f5ef
  encauth: 5660be18c9e080d3dd7aba18:ee4cfc2c8c66866cf7b5757f11aeb1a1:089b87387e9bc41815d2519a0e381497dfd28a99971967bc878a55122d0aea95
  'id: ': 2
- 'auth: ': 963239e4b156e02baf880b09f64282c6
  encauth: 33864aaa1d347c206a22736e:b76877194b47c51f445ec780ded1970f:349be95e528cad84733ff1935d4cc6fa4749fc35dce265fbb7f6fa129e2a3e21
  'id: ': 3
- 'auth: ': c32fa9338888bff86823dacae86451a0
  encauth: eabf6da300809c1747a04534:54d285a61f420d73cf1fe81ee15a55a1:0173325720b2cec0408ef50df4468ed31740f825d1fe6143ccf385ac40922396
  'id: ': 4
- 'auth: ': null
  encauth: null
  'id: ': 5
- 'auth: ': 4a07cca7d9105d79e98ba4ee292539de
  encauth: 5d6625193f33385a06f2c3e8:1a63ddc4076ad56d5885b45ee04c6cd0:9dd957cfc2ba983f4a4604f98bc4468eeaf98965f601395456e2cdebc26843d0
  'id: ': 6
- 'auth: ': null
  encauth: null
  'id: ': 7
- 'auth: ': 95d88a2b3930bc8a55867ccda79853f8
  encauth: 0b4977acfd160f4eb09a5576:223cdff7361a6582af69913207b793b6:d22c8efecbe49f4c60dd26022ae9dee3b95d5b89b8c671bfd45e4464ae180fdd
  'id: ': 8
- 'auth: ': null
  encauth: null
  'id: ': 9
- 'auth: ': 184a7b86acc7715a70323d47785d3465
  encauth: 9fc006ccc81b81caa1638945:6d5f276958139abda09d194b5d166364:bffafad3e18fb8b5e0267e2d7aa79801a919271f13a3476cedacede62af060da
  'id: ': 10
- 'auth: ': null
  encauth: null
  'id: ': 11
- 'auth: ': 93b9ff223d2a7e556c2f90240c523f61
  encauth: b8932719351597212f688169:e01d45ab49acf2d5a63558fdc1011a5c:845617e8f4eddf0413eca651b20654ce6e2f0d64b23d2b5014b09ecc667e1c9e
  'id: ': 12
- 'auth: ': null
  encauth: null
  'id: ': 13
pin:
  so:
    seal-auth: 19ada56c76bd583d619aef56a828f4fc
  user:
    seal-auth: ab03a8803ae33ce982b54bef577a9f88
wrappingkey:
  auth: ab03a8803ae33ce982b54bef577a9f88
  hex: '66616434666339363739323264613635643261373735636337346639643335656536303430616164363038363231333837313935393330646138313865323433'
  soauth: 19ada56c76bd583d619aef56a828f4fc

engine "pkcs11" set.
p11_pkey.c:528 pkcs11_try_pkey_ec_sign() not implemented
engine "pkcs11" set.
Adding EC Certificate
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 297, in _testValue
    raise error.ValueConstraintError(value)
pyasn1.type.error.ValueConstraintError: Extensions:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 32, in __call__
    self._testValue(value, idx)
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 497, in _testValue
    constraint(value, idx)
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 36, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: <ValueSizeConstraint object at 0xb5da2d30 consts 1, inf> failed at: ValueConstraintError(<Extensions value object at 0xb5d02a10 tagSet=<TagSet object at 0xb5daf9f0 tags 0:32:16-128:32:3> subtypeSpec=<ConstraintsIntersection object at 0xb5eddf10> componentType=<Extension schema object at 0xb5da2cd0 tagSet=<TagSet object at 0xb5e69110 tags 0:32:16> subtypeSpec=<ConstraintsIntersection object at 0xb5e69190> componentType=<NamedTypes object at 0xb5da2ab0 types <NamedType object at 0xb5da29d0 type extnID=<ObjectIdentifier schema object at 0xb5da2970 tagSet <TagSet object at 0xb5eddbf0 tags 0:0:6>>>, <DefaultedNamedType object at 0xb5da2a30 type critical=<Boolean value object at 0xb5da29f0 tagSet <TagSet object at 0xb5edd6f0 tags 0:0:1> subtypeSpec <ConstraintsIntersection object at 0xb5edd790 consts <SingleValueConstraint object at 0xb5edd770 consts 0, 1>> namedValues <NamedValues object 0xb5edd7d0 enums False=0, True=1> payload [False]>>, <NamedType object at 0xb5da2a90 type extnValue=<OctetString schema object at 0xb5da2a50 tagSet <TagSet object at 0xb5edd990 tags 0:0:4> encoding iso-8859-1> openType: <pyasn1.type.opentype.OpenType object at 0xb5da2a70>>> sizeSpec=<ConstraintsIntersection object at 0xb5e691b0>> sizeSpec=<ConstraintsIntersection object at 0xb5da2d50 consts <ValueSizeConstraint object at 0xb5da2d30 consts 1, inf>>>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
    main()
  File "/home/pi/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/home/pi/tpm2-pkcs11/tools/tpm2_pkcs11/command.py", line 102, in init
    commandlet.get()[d['which']](d)
  File "/home/pi/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_keys.py", line 301, in __call__
    attrs = pemcert_to_attrs(certpath)
  File "/home/pi/tpm2-pkcs11/tools/tpm2_pkcs11/utils.py", line 264, in pemcert_to_attrs
    bercert = b(cert)
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 663, in __call__
    substrate = concreteEncoder.encode(value, asn1Spec, self, **options)
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 85, in encode
    value, asn1Spec, encodeFun, **options
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 450, in encodeValue
    chunk = encodeFun(component, asn1Spec, **options)
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 663, in __call__
    substrate = concreteEncoder.encode(value, asn1Spec, self, **options)
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 85, in encode
    value, asn1Spec, encodeFun, **options
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 450, in encodeValue
    chunk = encodeFun(component, asn1Spec, **options)
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 663, in __call__
    substrate = concreteEncoder.encode(value, asn1Spec, self, **options)
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 85, in encode
    value, asn1Spec, encodeFun, **options
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/encoder.py", line 495, in encodeValue
    value.verifySizeSpec()
  File "/usr/lib/python3/dist-packages/pyasn1/type/base.py", line 619, in verifySizeSpec
    self.sizeSpec(self)
  File "/usr/lib/python3/dist-packages/pyasn1/type/constraint.py", line 36, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: <ConstraintsIntersection object at 0xb5da2d50 consts <ValueSizeConstraint object at 0xb5da2d30 consts 1, inf>> failed at: ValueConstraintError('<ValueSizeConstraint object at 0xb5da2d30 consts 1, inf> failed at: ValueConstraintError(<Extensions value object at 0xb5d02a10 tagSet=<TagSet object at 0xb5daf9f0 tags 0:32:16-128:32:3> subtypeSpec=<ConstraintsIntersection object at 0xb5eddf10> componentType=<Extension schema object at 0xb5da2cd0 tagSet=<TagSet object at 0xb5e69110 tags 0:32:16> subtypeSpec=<ConstraintsIntersection object at 0xb5e69190> componentType=<NamedTypes object at 0xb5da2ab0 types <NamedType object at 0xb5da29d0 type extnID=<ObjectIdentifier schema object at 0xb5da2970 tagSet <TagSet object at 0xb5eddbf0 tags 0:0:6>>>, <DefaultedNamedType object at 0xb5da2a30 type critical=<Boolean value object at 0xb5da29f0 tagSet <TagSet object at 0xb5edd6f0 tags 0:0:1> subtypeSpec <ConstraintsIntersection object at 0xb5edd790 consts <SingleValueConstraint object at 0xb5edd770 consts 0, 1>> namedValues <NamedValues object 0xb5edd7d0 enums False=0, True=1> payload [False]>>, <NamedType object at 0xb5da2a90 type extnValue=<OctetString schema object at 0xb5da2a50 tagSet <TagSet object at 0xb5edd990 tags 0:0:4> encoding iso-8859-1> openType: <pyasn1.type.opentype.OpenType object at 0xb5da2a70>>> sizeSpec=<ConstraintsIntersection object at 0xb5e691b0>> sizeSpec=<ConstraintsIntersection object at 0xb5da2d50 consts <ValueSizeConstraint object at 0xb5da2d30 consts 1, inf>>>)')
Failed to run the setup script
/P_RSA/HS/SRK:/P_RSA/HS:/P_RSA/HN:/P_RSA/HE/EK:/P_RSA/HE:/P_RSA/LOCKOUTExecution of ./test/integration/pkcs-login-logout.int failed: 1
FAIL test/integration/pkcs-login-logout.int (exit status: 1)

```

**Comment by williamcroberts** [comment]
I have no idea :-p
